/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/home/product_details" |
       "/pages/cart/index" |
       "/pages/home/address_list" |
       "/pages/home/event_egistration" |
       "/pages/home/group_buying" |
       "/pages/home/index" |
       "/pages/home/mbti_questiton" |
       "/pages/home/order_checkout" |
       "/pages/home/order_details" |
       "/pages/home/pet_mbti" |
       "/pages/home/privacy_policy" |
       "/pages/home/product_list" |
       "/pages/home/star_answer" |
       "/pages/home/store_address" |
       "/pages/login/index" |
       "/pages/personal/identityInfo" |
       "/pages/personal/index" |
       "/pages/personal/orders" |
       "/pages/personal/petIDCardList" |
       "/pages/report/index" |
       "/pages/report/report-result";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/report/index" | "/pages/home/product_list" | "/pages/personal/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
